const fs=require('fs'); const path=require('path'); const { execFile }=require('child_process'); const { promisify }=require('util'); const execFileAsync=promisify(execFile);
const { ensureRegistry, getActive, addVersion, setActive } = require('./modelRegistry');
const { loadJsonIfExists, compareMetrics } = require('./performance');
const { reloadActiveModel } = require('./ai');
function paths(ctx){ const root=ctx.CONFIG.projectRoot; return { root, journalFile:path.join(root,'data','journal','trades.jsonl'), datasetFile:path.join(root,'data','datasets','candidate_dataset.csv'), reportsDir:path.join(root,'data','reports'), registryDir:path.join(root,'model','registry') }; }
function versionStamp(){ const d=new Date(); const p=n=>String(n).padStart(2,'0'); return `v18.${d.getUTCFullYear()}${p(d.getUTCMonth()+1)}${p(d.getUTCDate())}-${p(d.getUTCHours())}${p(d.getUTCMinutes())}${p(d.getUTCSeconds())}`; }
function ensureDirs(ctx){ const p=paths(ctx); fs.mkdirSync(p.reportsDir,{recursive:true}); fs.mkdirSync(path.join(ctx.CONFIG.projectRoot,'data','datasets'),{recursive:true}); ensureRegistry(ctx.CONFIG.projectRoot); }
async function buildDataset(ctx){ ensureDirs(ctx); const p=paths(ctx); let lines=[]; if(fs.existsSync(p.journalFile)){ lines=fs.readFileSync(p.journalFile,'utf8').split('\n').filter(Boolean).map(l=>JSON.parse(l)); } const rows=['close,rsi14,ema20,ema50,ema_spread,atr14,vol_z,ret1,label']; for(const t of lines){ if(t.event!=='OPEN' || !t.featuresAtEntry) continue; const f=t.featuresAtEntry; let label=2; if((t.decision?.action||'')==='BUY') label=0; if((t.decision?.action||'')==='SELL') label=1; const emaSpread=((Number(f.ema20||0)-Number(f.ema50||0))/Math.max(1,Number(f.price||f.close||1))); rows.push([Number(f.price||f.close||0), Number(f.rsi||50)/100, Number(f.ema20||0), Number(f.ema50||0), emaSpread, Number(f.atr||0)/Math.max(1,Number(f.price||f.close||1)), Number(f.volRatio||1)-1, 0, label].join(',')); } fs.writeFileSync(p.datasetFile, rows.join('\n')); return p.datasetFile; }
async function runPython(ctx, scriptName, args=[]){ const scriptPath=path.join(ctx.CONFIG.projectRoot,'model',scriptName); const pythonCmd=process.platform==='win32' ? 'python' : 'python3'; return execFileAsync(pythonCmd,[scriptPath,...args],{ cwd:path.join(ctx.CONFIG.projectRoot,'model') }); }
async function trainCandidate(ctx, version){ const p=paths(ctx); const candidateDir=path.join(p.registryDir,version); fs.mkdirSync(candidateDir,{recursive:true}); await runPython(ctx,'retrain.py',['--dataset',p.datasetFile,'--outdir',candidateDir]); return candidateDir; }
async function evaluateCandidate(ctx, version){ const p=paths(ctx); const candidateDir=path.join(p.registryDir,version); const out=path.join(p.reportsDir,`${version}.metrics.json`); await runPython(ctx,'evaluate.py',['--dataset',p.datasetFile,'--modeldir',candidateDir,'--out',out]); return out; }
function currentLivePaperMetrics(ctx){ return { trades:ctx.state.stats.totalTrades, netPnl:ctx.state.stats.pnl, winRate:ctx.state.stats.winRate, maxDrawdownPct:ctx.helpers.drawdownPct() }; }
async function maybeRunTrainingCycle(ctx, force=false){ ensureDirs(ctx); if(ctx.state.training?.running) return { skipped:true, reason:'ALREADY_RUNNING' }; const now=Date.now(); if(!ctx.state.training) ctx.state.training={}; if(!force && ctx.state.training.lastRunAt && (now-ctx.state.training.lastRunAt) < Number(process.env.TRAIN_INTERVAL_MS||21600000)*0.9) return { skipped:true, reason:'TOO_SOON' }; ctx.state.training.running=true; ctx.state.training.lastRunAt=now; const version=versionStamp(); ctx.state.training.candidateVersion=version; try{ await buildDataset(ctx); const candidateDir=await trainCandidate(ctx,version); const metricsPath=await evaluateCandidate(ctx,version); const candidateMetrics=loadJsonIfExists(metricsPath,null); if(candidateMetrics){ candidateMetrics.livePaper=currentLivePaperMetrics(ctx); fs.writeFileSync(metricsPath, JSON.stringify(candidateMetrics,null,2)); }
const active=getActive(ctx.CONFIG.projectRoot); const currentMetrics=active?.metricsPath ? loadJsonIfExists(path.join(ctx.CONFIG.projectRoot, active.metricsPath), null) : null; addVersion(ctx.CONFIG.projectRoot,{ version, createdAt:new Date().toISOString(), status:'candidate', path:path.relative(ctx.CONFIG.projectRoot, path.join(candidateDir,'model.json')), metricsPath:path.relative(ctx.CONFIG.projectRoot, metricsPath) }); const decision=compareMetrics(currentMetrics, candidateMetrics, { validationAccuracyFloor:Number(process.env.VALIDATION_ACCURACY_FLOOR||0.45), minPromotionTrades:Number(process.env.MIN_PROMOTION_TRADES||30), modelPromotionMinPnlDelta:Number(process.env.MODEL_PROMOTION_MIN_PNL_DELTA||0) }); let promoted=false; if(decision.promote){ setActive(ctx.CONFIG.projectRoot,{ version, path:path.relative(ctx.CONFIG.projectRoot, path.join(candidateDir,'model.json')), metricsPath:path.relative(ctx.CONFIG.projectRoot, metricsPath) }); await reloadActiveModel(ctx); promoted=true; ctx.helpers.pushLog('INFO','Candidate promoted to active model',{version}); } else { ctx.helpers.pushLog('INFO','Candidate not promoted',{version,reasons:decision.reasons}); }
const result={ promoted, version, metricsPath, decision }; ctx.state.training.lastResult=result; return result; } finally { ctx.state.training.running=false; } }
function getTrainingStatus(ctx){ return ctx.state.training || {}; }
module.exports={ maybeRunTrainingCycle, getTrainingStatus };
